# Generated by Django 6.1 on 2026-08-12 01:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_dex_number', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1025)])),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['national_dex_number'],
            },
        ),
        migrations.CreateModel(
            name='PokemonGenerationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('version_group', models.CharField(choices=[('red-blue', 'Red/Blue')], max_length=30)),
                ('catch_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('sprite_url', models.URLField(blank=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_data', to='pokemon.pokemon')),
            ],
            options={
                'verbose_name': 'Pokémon generation data',
                'verbose_name_plural': 'Pokémon generation data',
                'ordering': ['generation', 'pokemon__national_dex_number'],
                'constraints': [models.UniqueConstraint(fields=('pokemon', 'generation', 'version_group'), name='unique_pokemon_generation_version')],
            },
        ),
    ]
