# Generated by Django 6.1 on 2026-08-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemongenerationdata',
            name='version_group',
            field=models.CharField(choices=[('red-blue', 'Red/Blue'), ('gold-silver', 'Gold/Silver'), ('crystal', 'Crystal')], max_length=30),
        ),
    ]
